import os
import re
import shutil
import tempfile
from datetime import datetime

from PyQt5.QtCore import QObject, pyqtSignal, Qt, QCoreApplication
from PyQt5.QtGui import QFont, QColor, QPainter, QPixmap
from PyQt5.QtSvg import QSvgRenderer

from database.db_manager import DatabaseManager

MAX_LOGO_BYTES = 5 * 1024 * 1024
ALLOWED_LOGO_EXTENSIONS = {".png", ".jpg", ".jpeg", ".svg"}
COMPANY_LOGO_DIR = os.path.join("assets", "company")
DEFAULT_LOGO_DIR = os.path.join("assets", "branding")
DEFAULT_LOGO_PATH = os.path.join(DEFAULT_LOGO_DIR, "vex_default.png")
PDF_LOGO_CACHE = os.path.join(COMPANY_LOGO_DIR, "logo_pdf.png")

DEFAULT_PROFILE = {
    "company_name": "VEX TESTING LABS",
    "company_logo": "",
    "address": "",
    "city": "",
    "state": "",
    "country": "",
    "postal_code": "",
    "phone": "",
    "email": "",
    "website": "",
    "authorized_by": "",
    "footer_text": (
        "Confidential Laboratory Report\n"
        "Generated by Video Extensometer Software"
    ),
    "report_title": "VIDEO EXTENSOMETER TEST REPORT",
    "gst_number": "",
}

PROFILE_FIELDS = [
    "company_name",
    "company_logo",
    "address",
    "city",
    "state",
    "country",
    "postal_code",
    "phone",
    "email",
    "website",
    "authorized_by",
    "footer_text",
    "report_title",
    "gst_number",
]

EMAIL_PATTERN = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")


class CompanyManager(QObject):
    """Singleton white-label company profile manager."""

    profile_updated = pyqtSignal()

    _instance = None

    def __new__(cls, *args, **kwargs):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
            cls._instance._initialized = False
        return cls._instance

    def __init__(self):
        if self._initialized:
            return
        super().__init__()
        self.db = DatabaseManager()
        self._ensure_directories()
        self._ensure_default_logo()
        self._initialized = True

    @classmethod
    def get_instance(cls):
        return cls()

    def get_profile(self):
        cur = self.db.conn.cursor()
        cur.execute(
            """
            SELECT company_name, company_logo, address, city, state, country,
                   postal_code, phone, email, website, authorized_by,
                   footer_text, report_title, gst_number
            FROM company_settings
            WHERE id = 1
            """
        )
        row = cur.fetchone()
        cur.close()

        profile = dict(DEFAULT_PROFILE)
        if row:
            for key, value in zip(PROFILE_FIELDS, row):
                profile[key] = value or ""

        logo_path = profile.get("company_logo") or ""
        if logo_path and os.path.isfile(logo_path):
            profile["company_logo"] = logo_path
        else:
            default_logo = self._ensure_default_logo()
            profile["company_logo"] = default_logo or ""
        return profile

    def has_custom_profile(self):
        cur = self.db.conn.cursor()
        cur.execute("SELECT 1 FROM company_settings WHERE id = 1")
        exists = cur.fetchone() is not None
        cur.close()
        return exists

    def save_profile(self, data, logo_source_path=None, remove_logo=False):
        errors = self.validate_profile(data)
        if errors:
            raise ValueError("\n".join(errors))

        cur = None
        try:
            with self.db._write_lock:
                cur = self.db.conn.cursor()
                cur.execute("BEGIN")

                logo_path = data.get("company_logo", "")
                if remove_logo:
                    self._delete_custom_logo_files()
                    logo_path = ""
                elif logo_source_path:
                    logo_path = self._store_logo_file(logo_source_path)

                now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                values = [data.get(field, "") for field in PROFILE_FIELDS]
                values[1] = logo_path

                cur.execute("SELECT 1 FROM company_settings WHERE id = 1")
                exists = cur.fetchone() is not None
                if exists:
                    cur.execute(
                        """
                        UPDATE company_settings SET
                            company_name=?, company_logo=?, address=?, city=?, state=?,
                            country=?, postal_code=?, phone=?, email=?, website=?,
                            authorized_by=?, footer_text=?, report_title=?,
                            gst_number=?, updated_at=?
                        WHERE id = 1
                        """,
                        values + [now],
                    )
                else:
                    cur.execute(
                        """
                        INSERT INTO company_settings(
                            id, company_name, company_logo, address, city, state,
                            country, postal_code, phone, email, website,
                            authorized_by, footer_text, report_title,
                            gst_number, created_at, updated_at
                        )
                        VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                        """,
                        values + [now, now],
                    )
                cur.execute("COMMIT")
            self.profile_updated.emit()
            return self.get_profile()
        except Exception:
            try:
                self.db.conn.rollback()
            except Exception:
                pass
            raise
        finally:
            if cur:
                cur.close()

    def restore_defaults(self):
        cur = None
        try:
            with self.db._write_lock:
                cur = self.db.conn.cursor()
                cur.execute("BEGIN")
                cur.execute("DELETE FROM company_settings WHERE id = 1")
                cur.execute("COMMIT")
            self._delete_custom_logo_files()
            self.profile_updated.emit()
        except Exception:
            try:
                self.db.conn.rollback()
            except Exception:
                pass
            raise
        finally:
            if cur:
                cur.close()

    @staticmethod
    def validate_profile(data):
        errors = []
        name = (data.get("company_name") or "").strip()
        if not name:
            errors.append("Company Name is required.")

        email = (data.get("email") or "").strip()
        if email and not EMAIL_PATTERN.match(email):
            errors.append("Email format is invalid.")

        phone = (data.get("phone") or "").strip()
        if phone:
            digits = re.sub(r"\D", "", phone)
            if len(digits) < 7:
                errors.append("Phone number must contain at least 7 digits.")

        return errors

    @staticmethod
    def validate_logo_file(file_path):
        if not file_path or not os.path.isfile(file_path):
            return "Logo file was not found."
        ext = os.path.splitext(file_path)[1].lower()
        if ext not in ALLOWED_LOGO_EXTENSIONS:
            return "Logo must be PNG, JPG, or SVG."
        if os.path.getsize(file_path) > MAX_LOGO_BYTES:
            return "Logo file exceeds the 5 MB limit."
        return None

    def get_logo_pixmap(self, max_width=200, max_height=80):
        if QCoreApplication.instance() is None:
            return None
        path = self.get_profile().get("company_logo", "")
        if not path or not os.path.isfile(path):
            return None
        if path.lower().endswith(".svg"):
            renderer = QSvgRenderer(path)
            if not renderer.isValid():
                return None
            size = renderer.defaultSize()
            if size.width() <= 0 or size.height() <= 0:
                size = renderer.viewBox().size()
            scale = min(
                max_width / max(size.width(), 1),
                max_height / max(size.height(), 1),
                1.0,
            )
            width = max(1, int(size.width() * scale))
            height = max(1, int(size.height() * scale))
            pixmap = QPixmap(width, height)
            pixmap.fill(Qt.transparent)
            painter = QPainter(pixmap)
            renderer.render(painter)
            painter.end()
            return pixmap

        pixmap = QPixmap(path)
        if pixmap.isNull():
            return None
        return pixmap.scaled(
            max_width,
            max_height,
            Qt.KeepAspectRatio,
            Qt.SmoothTransformation,
        )

    def get_pdf_logo_path(self):
        profile = self.get_profile()
        source = profile.get("company_logo", "")
        if not source or not os.path.isfile(source):
            source = self._ensure_default_logo()
        return self._prepare_pdf_logo(source)

    def format_address_block(self, profile=None):
        profile = profile or self.get_profile()
        parts = []
        if profile.get("address"):
            parts.append(profile["address"])
        city_line = ", ".join(
            p for p in [profile.get("city"), profile.get("state"), profile.get("postal_code")] if p
        )
        if city_line:
            parts.append(city_line)
        if profile.get("country"):
            parts.append(profile["country"])
        return "\n".join(parts)

    def format_contact_line(self, profile=None):
        profile = profile or self.get_profile()
        items = []
        if profile.get("phone"):
            items.append(f"Phone: {profile['phone']}")
        if profile.get("email"):
            items.append(f"Email: {profile['email']}")
        if profile.get("website"):
            items.append(f"Web: {profile['website']}")
        return "  |  ".join(items)

    def csv_header_rows(self, profile=None):
        profile = profile or self.get_profile()
        rows = [
            ["Company Profile"],
            ["Company Name", profile.get("company_name", "")],
        ]
        address = self.format_address_block(profile)
        if address:
            rows.append(["Address", address.replace("\n", ", ")])
        contact = self.format_contact_line(profile)
        if contact:
            rows.append(["Contact", contact])
        if profile.get("gst_number"):
            rows.append(["GST Number", profile["gst_number"]])
        if profile.get("authorized_by"):
            rows.append(["Authorized By", profile["authorized_by"]])
        rows.append([])
        return rows

    def _ensure_directories(self):
        os.makedirs(COMPANY_LOGO_DIR, exist_ok=True)
        os.makedirs(DEFAULT_LOGO_DIR, exist_ok=True)

    def _ensure_default_logo(self):
        if os.path.isfile(DEFAULT_LOGO_PATH):
            return DEFAULT_LOGO_PATH
        if QCoreApplication.instance() is None:
            return ""
        pixmap = QPixmap(220, 72)
        pixmap.fill(QColor("#cdcfc0"))
        painter = QPainter(pixmap)
        painter.setPen(QColor("#ffffff"))
        painter.setFont(QFont("Segoe UI", 22, QFont.Bold))
        painter.drawText(pixmap.rect(), Qt.AlignCenter, "VEX")
        painter.setPen(QColor("#bdcbdb"))
        painter.setFont(QFont("Segoe UI", 9, QFont.Bold))
        painter.drawText(
            pixmap.rect().adjusted(0, 24, 0, 0),
            Qt.AlignHCenter | Qt.AlignTop,
            "TESTING LABS",
        )
        painter.end()
        pixmap.save(DEFAULT_LOGO_PATH, "PNG")
        return DEFAULT_LOGO_PATH

    def _store_logo_file(self, source_path):
        error = self.validate_logo_file(source_path)
        if error:
            raise ValueError(error)
        self._delete_custom_logo_files()
        ext = os.path.splitext(source_path)[1].lower()
        dest = os.path.join(COMPANY_LOGO_DIR, f"company_logo{ext}")
        shutil.copy2(source_path, dest)
        return dest.replace("\\", "/")

    def _delete_custom_logo_files(self):
        if not os.path.isdir(COMPANY_LOGO_DIR):
            return
        for name in os.listdir(COMPANY_LOGO_DIR):
            if name.startswith("company_logo"):
                try:
                    os.remove(os.path.join(COMPANY_LOGO_DIR, name))
                except OSError:
                    pass
        if os.path.isfile(PDF_LOGO_CACHE):
            try:
                os.remove(PDF_LOGO_CACHE)
            except OSError:
                pass

    def _prepare_pdf_logo(self, source_path):
        if not source_path or not os.path.isfile(source_path):
            source_path = self._ensure_default_logo()
        if not source_path:
            return None
        if source_path.lower().endswith(".svg"):
            if QCoreApplication.instance() is None:
                return None
            renderer = QSvgRenderer(source_path)
            if not renderer.isValid():
                return self._ensure_default_logo()
            pixmap = QPixmap(240, 80)
            pixmap.fill(Qt.transparent)
            painter = QPainter(pixmap)
            renderer.render(painter)
            painter.end()
            pixmap.save(PDF_LOGO_CACHE, "PNG")
            return PDF_LOGO_CACHE

        pixmap = QPixmap(source_path)
        if pixmap.isNull():
            return self._ensure_default_logo()
        scaled = pixmap.scaled(
            240,
            80,
            Qt.KeepAspectRatio,
            Qt.SmoothTransformation,
        )
        scaled.save(PDF_LOGO_CACHE, "PNG")
        return PDF_LOGO_CACHE
