import os
import csv
import math
from datetime import datetime
from PyQt5 import QtWidgets, QtGui, QtCore

# ReportLab imports for professional PDF generation
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfgen import canvas

from database.report_manager import ReportManager, ReportClearPermissionError
from database.sample_manager import SampleManager
from database.audit_manager import AuditManager
from database.company_manager import CompanyManager
from ui.custom_dialog import CustomDialog
from ui.table_style import apply_enterprise_table_style, apply_dark_panel_style


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas renderer that dynamically calculates the total page count
    and draws a professional footer bar with page numbers, generation time,
    and software version details on every page.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_footer(num_pages)
            super().showPage()
        super().save()

    def draw_footer(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))

        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.setLineWidth(0.5)
        self.line(54, 45, 558, 45)

        profile = CompanyManager.get_instance().get_profile()
        footer_text = (profile.get("footer_text") or "").replace("\n", "  |  ")
        version_text = "Software Version: v2.5.0-industrial"
        gen_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        footer_left = footer_text or "Generated by Video Extensometer Software"
        footer_left = f"{footer_left}  |  {version_text}"
        footer_right = f"{gen_time}  |  Page {self._pageNumber} of {page_count}"

        self.drawString(54, 30, footer_left[:120])
        self.drawRightString(558, 30, footer_right)

        self.restoreState()


class TimelineDialog(QtWidgets.QDialog):
    """Professional dialog for browsing a report's measurement timeline."""

    def __init__(self, report, parent=None):
        super().__init__(parent)
        self.report = report
        self.sample_manager = SampleManager()
        self.all_samples = self.sample_manager.get_samples(report["id"])
        self.setWindowTitle(f"Test Timeline — Report #{report['id']}")
        self.setModal(True)
        self.resize(900, 560)
        self.setup_stylesheet()
        self.setup_ui()
        self.populate_table(self.all_samples)

    def setup_stylesheet(self):
        self.setStyleSheet("""
            QDialog { background-color: #0f172a; }
            QWidget { color: #f8fafc; font-family: 'Segoe UI', sans-serif; }
            QLineEdit {
                background-color: #1e293b;
                border: 1px solid #334155;
                border-radius: 6px;
                padding: 8px 12px;
                color: #f8fafc;
            }
            QPushButton {
                background-color: #3b82f6;
                color: white;
                border: none;
                border-radius: 6px;
                padding: 8px 16px;
                font-weight: bold;
            }
            QPushButton#secondary {
                background-color: #334155;
                border: 1px solid #475569;
            }
        """)

    def setup_ui(self):
        layout = QtWidgets.QVBoxLayout(self)
        layout.setContentsMargins(20, 20, 20, 20)
        layout.setSpacing(12)

        title = QtWidgets.QLabel(
            f"Measurement Timeline — {self.report.get('sample_name', 'N/A')}"
        )
        title.setStyleSheet("font-size: 16px; font-weight: bold;")
        layout.addWidget(title)

        self.search_input = QtWidgets.QLineEdit()
        self.search_input.setPlaceholderText("Search samples...")
        self.search_input.textChanged.connect(self.filter_samples)
        layout.addWidget(self.search_input)

        self.table = QtWidgets.QTableWidget()
        self.table.setColumnCount(5)
        self.table.setHorizontalHeaderLabels([
            "Sample #",
            "Elapsed Time (s)",
            "Distance (mm)",
            "Extension (mm)",
            "Strain",
        ])
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table.setSortingEnabled(True)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.horizontalHeader().setSectionResizeMode(
            QtWidgets.QHeaderView.Stretch
        )
        apply_enterprise_table_style(self.table, "timelineTable", row_height=36)
        layout.addWidget(self.table, 1)

        self.count_label = QtWidgets.QLabel()
        self.count_label.setStyleSheet("color: #94a3b8; font-size: 11px;")
        layout.addWidget(self.count_label)

        close_btn = QtWidgets.QPushButton("Close")
        close_btn.setObjectName("secondary")
        close_btn.clicked.connect(self.close)
        btn_row = QtWidgets.QHBoxLayout()
        btn_row.addStretch()
        btn_row.addWidget(close_btn)
        layout.addLayout(btn_row)

    def populate_table(self, samples):
        self.table.setSortingEnabled(False)
        self.table.setRowCount(len(samples))
        for row, sample in enumerate(samples):
            elapsed, distance, extension, strain = sample
            values = [
                str(row + 1),
                f"{elapsed:.3f}",
                f"{distance:.3f}",
                f"{extension:.3f}",
                f"{strain:+.6f}",
            ]
            for col, text in enumerate(values):
                item = QtWidgets.QTableWidgetItem(text)
                if col > 0:
                    item.setTextAlignment(
                        QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter
                    )
                self.table.setItem(row, col, item)
        self.table.setSortingEnabled(True)
        self.count_label.setText(f"{len(samples)} samples recorded")

    def filter_samples(self, text):
        query = text.strip().lower()
        if not query:
            self.populate_table(self.all_samples)
            return
        filtered = []
        for idx, sample in enumerate(self.all_samples):
            elapsed, distance, extension, strain = sample
            haystack = (
                f"{idx + 1} {elapsed:.3f} {distance:.3f} "
                f"{extension:.3f} {strain:+.6f}"
            ).lower()
            if query in haystack:
                filtered.append(sample)
        self.populate_table(filtered)


class ReportDetailsDialog(QtWidgets.QDialog):
    """
    Professional report details dialog displaying general metadata,
    strain/gauge measurements, calibration inputs, and operator remarks in a structured tab.
    """
    def __init__(self, report, parent=None):
        super().__init__(parent)
        self.report = report  # Dict containing report columns
        self.report_manager = ReportManager()
        self.sample_manager = SampleManager()
        self.timeline_stats = self.sample_manager.get_timeline_stats(report["id"])
        self.setWindowTitle(f"Report Detail - Specimen: {self.report.get('sample_name', 'N/A')}")
        self.setModal(True)
        self.resize(720, 640)

        self.setup_stylesheet()
        self.setup_ui()

    def setup_stylesheet(self):
        self.setStyleSheet("""
            QDialog {
                background-color: #0f172a;
            }
            QWidget#reportDetailsContent {
                background-color: #0f172a;
            }
            QScrollArea {
                background-color: #0f172a;
                border: none;
            }
            QScrollArea > QWidget > QWidget {
                background-color: #0f172a;
            }
            QWidget {
                color: #f8fafc;
                font-family: 'Segoe UI', -apple-system, sans-serif;
            }
            QFrame#sectionCard {
                background-color: #1e293b;
                border: 1px solid #334155;
                border-radius: 8px;
            }
            QLabel#sectionTitle {
                font-size: 11px;
                font-weight: bold;
                color: #38bdf8;
                text-transform: uppercase;
                letter-spacing: 0.5px;
                background-color: transparent;
            }
            QLabel#label {
                font-size: 11px;
                font-weight: bold;
                color: #94a3b8;
                text-transform: uppercase;
                background-color: transparent;
            }
            QLabel#value {
                font-size: 13px;
                color: #f8fafc;
                font-weight: bold;
                background-color: transparent;
            }
            QLabel#pageTitle {
                font-size: 16px;
                font-weight: bold;
                color: #f8fafc;
                letter-spacing: 0.5px;
                background-color: transparent;
            }
            QPlainTextEdit#remarksBox {
                background-color: #0f172a;
                border: 1px solid #334155;
                border-radius: 6px;
                color: #e2e8f0;
                font-size: 12px;
                padding: 6px;
            }
            QPushButton {
                background-color: #3b82f6;
                color: white;
                border: none;
                border-radius: 6px;
                padding: 8px 16px;
                font-weight: bold;
                font-size: 12px;
            }
            QPushButton:hover {
                background-color: #2563eb;
            }
            QPushButton#secondary {
                background-color: #334155;
                color: #f8fafc;
                border: 1px solid #475569;
            }
            QPushButton#secondary:hover {
                background-color: #475569;
            }
        """)

    def setup_ui(self):
        scroll = QtWidgets.QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        scroll.setAttribute(QtCore.Qt.WA_StyledBackground, True)

        content = QtWidgets.QWidget()
        content.setObjectName("reportDetailsContent")
        content.setAttribute(QtCore.Qt.WA_StyledBackground, True)
        main_layout = QtWidgets.QVBoxLayout(content)
        main_layout.setContentsMargins(20, 20, 20, 20)
        main_layout.setSpacing(16)

        # 1. Title Block
        title_lbl = QtWidgets.QLabel("TEST SEQUENCE ANALYSIS")
        title_lbl.setObjectName("pageTitle")
        main_layout.addWidget(title_lbl)
        
        # 2. General Information Section (Card)
        gen_card = QtWidgets.QFrame()
        gen_card.setObjectName("sectionCard")
        gen_layout = QtWidgets.QVBoxLayout(gen_card)
        gen_layout.setContentsMargins(14, 14, 14, 14)
        
        gen_title = QtWidgets.QLabel("General Information")
        gen_title.setObjectName("sectionTitle")
        gen_layout.addWidget(gen_title)
        
        gen_grid = QtWidgets.QGridLayout()
        gen_grid.setSpacing(10)
        
        def add_field(grid, lbl_text, val_text, row, col):
            lbl = QtWidgets.QLabel(lbl_text)
            lbl.setObjectName("label")
            val = QtWidgets.QLabel(val_text)
            val.setObjectName("value")
            grid.addWidget(lbl, row * 2, col)
            grid.addWidget(val, row * 2 + 1, col)

        add_field(gen_grid, "Report ID", str(self.report['id']), 0, 0)
        add_field(gen_grid, "Operator", self.report['operator'], 0, 1)
        add_field(gen_grid, "Material", self.report['material'], 0, 2)
        add_field(gen_grid, "Sample Name", self.report['sample_name'], 1, 0)
        add_field(gen_grid, "Test Name", self.report['test_name'], 1, 1)
        add_field(gen_grid, "Date & Time", self.report['created_at'], 1, 2)
        
        gen_layout.addLayout(gen_grid)
        main_layout.addWidget(gen_card)
        
        # 3. Measurements Section (Card)
        meas_card = QtWidgets.QFrame()
        meas_card.setObjectName("sectionCard")
        meas_layout = QtWidgets.QVBoxLayout(meas_card)
        meas_layout.setContentsMargins(14, 14, 14, 14)
        
        meas_title = QtWidgets.QLabel("Measurements")
        meas_title.setObjectName("sectionTitle")
        meas_layout.addWidget(meas_title)
        
        meas_grid = QtWidgets.QGridLayout()
        meas_grid.setSpacing(10)
        
        ext_val = self.report['final_distance'] - self.report['initial_distance']
        strain_val = self.report['strain']
        duration = self.timeline_stats.get("test_duration")
        duration_text = SampleManager.format_duration(duration)

        add_field(meas_grid, "Gauge Length", f"{self.report['gauge_length']:.2f} mm", 0, 0)
        add_field(meas_grid, "Final Distance", f"{self.report['final_distance']:.2f} mm", 0, 1)
        add_field(meas_grid, "Final Strain (ε)", f"{strain_val:+.6f}", 0, 2)
        add_field(meas_grid, "Extension (Δd)", f"{ext_val:+.2f} mm", 1, 0)
        add_field(meas_grid, "Test Duration", duration_text, 1, 1)

        meas_layout.addLayout(meas_grid)
        main_layout.addWidget(meas_card)

        # 4. Timeline Statistics
        stats = self.timeline_stats
        timeline_card = QtWidgets.QFrame()
        timeline_card.setObjectName("sectionCard")
        timeline_layout = QtWidgets.QVBoxLayout(timeline_card)
        timeline_layout.setContentsMargins(14, 14, 14, 14)

        timeline_title = QtWidgets.QLabel("Timeline Statistics")
        timeline_title.setObjectName("sectionTitle")
        timeline_layout.addWidget(timeline_title)

        timeline_grid = QtWidgets.QGridLayout()
        timeline_grid.setSpacing(10)

        def fmt_strain(val):
            return f"{val:+.6f}" if val is not None else "—"

        def fmt_ext(val):
            return f"{val:+.3f} mm" if val is not None else "—"

        add_field(
            timeline_grid,
            "Total Samples Recorded",
            str(stats.get("total_samples", 0)),
            0, 0,
        )
        add_field(
            timeline_grid,
            "Maximum Strain",
            fmt_strain(stats.get("max_strain")),
            0, 1,
        )
        add_field(
            timeline_grid,
            "Average Strain",
            fmt_strain(stats.get("avg_strain")),
            0, 2,
        )
        add_field(
            timeline_grid,
            "Maximum Extension",
            fmt_ext(stats.get("max_extension")),
            1, 0,
        )
        add_field(
            timeline_grid,
            "Average Extension",
            fmt_ext(stats.get("avg_extension")),
            1, 1,
        )
        add_field(
            timeline_grid,
            "Test Duration",
            duration_text,
            1, 2,
        )

        timeline_layout.addLayout(timeline_grid)
        main_layout.addWidget(timeline_card)

        # 5. Metrology & Remarks (Card)
        system_card = QtWidgets.QFrame()
        system_card.setObjectName("sectionCard")
        system_layout = QtWidgets.QVBoxLayout(system_card)
        system_layout.setContentsMargins(14, 14, 14, 14)
        
        system_title = QtWidgets.QLabel("Tracking Configuration & Remarks")
        system_title.setObjectName("sectionTitle")
        system_layout.addWidget(system_title)
        
        system_grid = QtWidgets.QGridLayout()
        system_grid.setSpacing(8)
        add_field(system_grid, "Camera Resolution", self.report['camera_resolution'], 0, 0)
        add_field(system_grid, "Software Version", self.report['software_version'], 0, 1)
        add_field(system_grid, "System User Account", self.report['username'], 0, 2)
        system_layout.addLayout(system_grid)
        
        remarks_lbl = QtWidgets.QLabel("Remarks:")
        remarks_lbl.setObjectName("label")
        system_layout.addWidget(remarks_lbl)
        
        self.remarks_box = QtWidgets.QPlainTextEdit()
        self.remarks_box.setObjectName("remarksBox")
        self.remarks_box.setPlainText(self.report['remarks'] if self.report['remarks'] else "No comments entered.")
        self.remarks_box.setReadOnly(True)
        self.remarks_box.setMaximumHeight(60)
        system_layout.addWidget(self.remarks_box)
        
        main_layout.addWidget(system_card)
        
        scroll.setWidget(content)
        scroll.viewport().setStyleSheet("background-color: #0f172a;")

        outer = QtWidgets.QVBoxLayout(self)
        outer.setContentsMargins(0, 0, 0, 0)
        outer.addWidget(scroll)

        # Action buttons fixed below scroll area
        btn_bar = QtWidgets.QWidget()
        btn_bar.setObjectName("reportDetailsContent")
        btn_bar.setAttribute(QtCore.Qt.WA_StyledBackground, True)
        btn_layout = QtWidgets.QHBoxLayout(btn_bar)
        btn_layout.setContentsMargins(20, 12, 20, 16)
        btn_layout.setSpacing(10)

        self.timeline_btn = QtWidgets.QPushButton("View Timeline")
        self.timeline_btn.clicked.connect(self.open_timeline)

        self.pdf_btn = QtWidgets.QPushButton("Generate PDF")
        self.pdf_btn.clicked.connect(self.generate_pdf)

        self.csv_btn = QtWidgets.QPushButton("Export CSV")
        self.csv_btn.setObjectName("secondary")
        self.csv_btn.clicked.connect(self.export_csv)

        self.close_btn = QtWidgets.QPushButton("Close")
        self.close_btn.setObjectName("secondary")
        self.close_btn.clicked.connect(self.close)

        btn_layout.addWidget(self.timeline_btn)
        btn_layout.addWidget(self.pdf_btn)
        btn_layout.addWidget(self.csv_btn)
        btn_layout.addStretch()
        btn_layout.addWidget(self.close_btn)
        outer.addWidget(btn_bar)

    def open_timeline(self):
        TimelineDialog(self.report, self).exec_()

    def generate_pdf(self):
        """Invoke parent page's PDF rendering workflow for this report."""
        if hasattr(self.parent(), "render_report_pdf"):
            self.parent().render_report_pdf(self.report)
            
    def export_csv(self):
        """Invoke parent page's CSV rendering workflow for this report."""
        if hasattr(self.parent(), "render_report_csv"):
            self.parent().render_report_csv(self.report)


class ReportsPage(QtWidgets.QWidget):
    """
    Redesigned reports dashboard. Provides a corporate layout featuring:
    - Stats widgets for Total Reports and selection-based Average Strain.
    - Query filters and Search/Reset triggers.
    - Table with alternating row colors, sorting, pagination, colored status badges, and Action column buttons.
    - Double-click details modal dialog.
    - Custom ReportLab styled PDF generation and CSV exports.
    """
    def __init__(self, user=None):
        super().__init__()
        self.user = user
        self.report_manager = ReportManager()
        self.sample_manager = SampleManager()
        self.audit = AuditManager.get_instance()
        
        # State variables
        self.all_reports = []       # Query matching reports
        self.current_page = 1
        self.items_per_page = 10
        self.total_pages = 1
        self.keep_page_on_reload = False
        
        self.setup_ui()
        self.setup_stylesheet()
        
        # Initial database load
        self.load_reports()

    def setup_stylesheet(self):
        self.setStyleSheet("""
            QWidget {
                color: #f8fafc;
                font-family: 'Segoe UI', -apple-system, sans-serif;
            }
            QFrame#statCard {
                background-color: #1e293b;
                border: 1px solid #334155;
                border-radius: 10px;
            }
            QFrame#searchCard {
                background-color: #1e293b;
                border: 1px solid #334155;
                border-radius: 8px;
            }
            QLabel#statTitle {
                font-size: 10px;
                font-weight: bold;
                color: #94a3b8;
                letter-spacing: 1px;
            }
            QLabel#searchLabel {
                font-size: 11px;
                font-weight: bold;
                color: #94a3b8;
                text-transform: uppercase;
            }
            QLineEdit {
                background-color: #0f172a;
                border: 1px solid #334155;
                border-radius: 6px;
                padding: 6px 10px;
                color: #f8fafc;
                font-size: 12px;
            }
            QLineEdit:focus {
                border-color: #3b82f6;
            }
            QPushButton {
                background-color: #3b82f6;
                color: white;
                border: none;
                border-radius: 6px;
                padding: 8px 16px;
                font-weight: bold;
                font-size: 12px;
            }
            QPushButton:hover {
                background-color: #2563eb;
            }
            QPushButton#secondary {
                background-color: #334155;
                color: #f8fafc;
                border: 1px solid #475569;
            }
            QPushButton#secondary:hover {
                background-color: #475569;
            }
            QPushButton#tableActionBtn {
                background-color: #334155;
                color: #f8fafc;
                border: 1px solid #475569;
                border-radius: 4px;
                font-size: 10px;
                font-weight: bold;
                padding: 3px 6px;
            }
            QPushButton#tableActionBtn:hover {
                background-color: #475569;
            }
            QPushButton#tableActionDeleteBtn {
                background-color: #7f1d1d;
                color: #fecaca;
                border: 1px solid #991b1b;
                border-radius: 4px;
                font-size: 10px;
                font-weight: bold;
                padding: 3px 6px;
            }
            QPushButton#tableActionDeleteBtn:hover {
                background-color: #991b1b;
            }
            QPushButton#clearAllBtn {
                background-color: #7f1d1d;
                color: #fecaca;
                border: 1px solid #991b1b;
            }
            QPushButton#clearAllBtn:hover {
                background-color: #991b1b;
            }
            QStackedWidget {
                background-color: #1E293B;
                border: none;
            }
        """)

    def setup_ui(self):
        main_layout = QtWidgets.QVBoxLayout(self)
        main_layout.setContentsMargins(0, 0, 0, 0)
        main_layout.setSpacing(16)
        
        # ==========================================
        # 1. STATS CARDS ROW
        # ==========================================
        stats_layout = QtWidgets.QHBoxLayout()
        stats_layout.setSpacing(16)

        def create_kpi_card(title, initial_value="—", value_size=32, value_color="#f8fafc"):
            card = QtWidgets.QFrame()
            card.setObjectName("statCard")
            card.setFixedHeight(118)
            card.setSizePolicy(
                QtWidgets.QSizePolicy.Expanding,
                QtWidgets.QSizePolicy.Fixed,
            )

            lyt = QtWidgets.QVBoxLayout(card)
            lyt.setContentsMargins(18, 16, 18, 16)
            lyt.setSpacing(6)

            title_lbl = QtWidgets.QLabel(title)
            title_lbl.setStyleSheet(
                "font-size: 10px; color: #94a3b8; font-weight: bold; letter-spacing: 1px;"
            )

            val_lbl = QtWidgets.QLabel(initial_value)
            val_lbl.setStyleSheet(
                f"font-size: {value_size}px; font-weight: bold; color: {value_color};"
            )
            val_lbl.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)

            lyt.addWidget(title_lbl)
            lyt.addStretch()
            lyt.addWidget(val_lbl)
            lyt.addStretch()
            return card, val_lbl

        self.card_total, self.val_total = create_kpi_card("TOTAL REPORTS", "0")
        self.card_avg_strain, self.val_avg_strain = create_kpi_card(
            "AVERAGE STRAIN",
            "—",
            value_size=13,
            value_color="#64748b",
        )

        stats_layout.addWidget(self.card_total, 1)
        stats_layout.addWidget(self.card_avg_strain, 1)
        main_layout.addLayout(stats_layout)
        
        # ==========================================
        # 2. SEARCH & FILTERS CARD
        # ==========================================
        search_card = QtWidgets.QFrame()
        search_card.setObjectName("searchCard")
        search_card_layout = QtWidgets.QVBoxLayout(search_card)
        search_card_layout.setContentsMargins(14, 12, 14, 12)
        search_card_layout.setSpacing(10)
        
        search_title = QtWidgets.QLabel("FILTER DATABASE REPORTS")
        search_title.setStyleSheet("font-size: 11px; font-weight: bold; color: #38bdf8; letter-spacing: 0.5px;")
        search_card_layout.addWidget(search_title)
        
        inputs_box = QtWidgets.QHBoxLayout()
        inputs_box.setSpacing(12)
        
        def add_search_input(box, label_text, placeholder):
            v_box = QtWidgets.QVBoxLayout()
            v_box.setSpacing(4)
            lbl = QtWidgets.QLabel(label_text)
            lbl.setObjectName("searchLabel")
            inp = QtWidgets.QLineEdit()
            inp.setPlaceholderText(placeholder)
            v_box.addWidget(lbl)
            v_box.addWidget(inp)
            box.addLayout(v_box)
            return inp
            
        self.filter_material = add_search_input(inputs_box, "Material", "e.g. Steel")
        self.filter_operator = add_search_input(inputs_box, "Operator / User", "e.g. Admin")
        self.filter_date = add_search_input(inputs_box, "Date", "YYYY-MM-DD")
        self.filter_sample = add_search_input(inputs_box, "Sample Name", "e.g. Specimen")
        self.filter_test = add_search_input(inputs_box, "Test Name", "e.g. Tensile")
        
        # Action Buttons Layout
        btn_box = QtWidgets.QVBoxLayout()
        btn_box.setSpacing(4)
        btn_box.addSpacing(16) # Align with input widgets vertical offset
        
        actions_row = QtWidgets.QHBoxLayout()
        actions_row.setSpacing(8)
        self.search_btn = QtWidgets.QPushButton("Search")
        self.search_btn.clicked.connect(self.on_search_clicked)
        
        self.reset_btn = QtWidgets.QPushButton("Reset")
        self.reset_btn.setObjectName("secondary")
        self.reset_btn.clicked.connect(self.on_reset_clicked)
        
        actions_row.addWidget(self.search_btn)
        actions_row.addWidget(self.reset_btn)
        btn_box.addLayout(actions_row)
        
        inputs_box.addLayout(btn_box)
        search_card_layout.addLayout(inputs_box)
        main_layout.addWidget(search_card)
        
        # ==========================================
        # 3. TABLE VIEW CARD & STACKED LOADING / EMPTY VIEW
        # ==========================================
        table_card = QtWidgets.QFrame()
        table_card.setObjectName("statCard") # reuse card styling
        table_card_layout = QtWidgets.QVBoxLayout(table_card)
        table_card_layout.setContentsMargins(12, 12, 12, 12)
        table_card_layout.setSpacing(10)
        
        # Stacked layout for loading animation, empty illustrations and actual table
        self.stacked_view = QtWidgets.QStackedWidget()
        apply_dark_panel_style(self.stacked_view)
        
        # Container 0: The Table widget itself
        self.table = QtWidgets.QTableWidget()
        self.table.setColumnCount(10)
        self.table.setHorizontalHeaderLabels([
            "ID", "Material", "Sample Name", "User",
            "Gauge Length", "Initial Distance", "Final Distance", "Strain", "Date", "Actions"
        ])
        
        # Layout spacing adjustments
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table.setSizePolicy(
            QtWidgets.QSizePolicy.Expanding,
            QtWidgets.QSizePolicy.Expanding,
        )
        self.table.itemSelectionChanged.connect(self.on_table_selection_changed)
        self.table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.table.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        self.table.horizontalHeader().setSectionResizeMode(8, QtWidgets.QHeaderView.ResizeToContents)
        self.table.horizontalHeader().setSectionResizeMode(9, QtWidgets.QHeaderView.Fixed)
        self.table.setColumnWidth(9, 210) # Enough space for action buttons
        
        # Double click connections
        self.table.doubleClicked.connect(self.on_row_double_clicked)
        
        # Sorting
        self.table.setSortingEnabled(True)
        apply_enterprise_table_style(self.table, "reportsTable", row_height=40)
        
        self.stacked_view.addWidget(self.table)
        
        # Container 1: Loading view
        self.loading_view = QtWidgets.QWidget()
        apply_dark_panel_style(self.loading_view)
        loading_layout = QtWidgets.QVBoxLayout(self.loading_view)
        self.loading_label = QtWidgets.QLabel("🔄   Loading database reports... Please wait")
        self.loading_label.setAlignment(QtCore.Qt.AlignCenter)
        self.loading_label.setStyleSheet("font-size: 15px; color: #fbbf24; font-weight: bold;")
        loading_layout.addWidget(self.loading_label)
        self.stacked_view.addWidget(self.loading_view)
        
        # Container 2: Empty state illustration
        self.empty_view = QtWidgets.QWidget()
        apply_dark_panel_style(self.empty_view)
        empty_layout = QtWidgets.QVBoxLayout(self.empty_view)
        empty_lbl1 = QtWidgets.QLabel("📂")
        empty_lbl1.setAlignment(QtCore.Qt.AlignCenter)
        empty_lbl1.setStyleSheet("font-size: 48px;")
        empty_lbl2 = QtWidgets.QLabel("NO LABORATORY REPORTS FOUND")
        empty_lbl2.setAlignment(QtCore.Qt.AlignCenter)
        empty_lbl2.setStyleSheet("font-size: 14px; font-weight: bold; color: #94a3b8;")
        empty_lbl3 = QtWidgets.QLabel("Adjust your search parameters above or initiate a new specimen tracking sequence.")
        empty_lbl3.setAlignment(QtCore.Qt.AlignCenter)
        empty_lbl3.setStyleSheet("font-size: 12px; color: #64748b;")
        
        empty_layout.addStretch()
        empty_layout.addWidget(empty_lbl1)
        empty_layout.addWidget(empty_lbl2)
        empty_layout.addWidget(empty_lbl3)
        empty_layout.addStretch()
        self.stacked_view.addWidget(self.empty_view)
        
        table_card_layout.addWidget(self.stacked_view, 1)
        
        # ==========================================
        # 4. PAGINATION ROW CONTROLS
        # ==========================================
        pagination_layout = QtWidgets.QHBoxLayout()
        pagination_layout.setSpacing(10)
        
        self.prev_btn = QtWidgets.QPushButton("◀ Previous")
        self.prev_btn.setObjectName("secondary")
        self.prev_btn.setFixedWidth(100)
        self.prev_btn.clicked.connect(self.go_prev_page)
        
        self.page_lbl = QtWidgets.QLabel("Page 1 of 1")
        self.page_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.page_lbl.setStyleSheet("font-size: 12px; font-weight: bold; color: #94a3b8;")
        
        self.next_btn = QtWidgets.QPushButton("Next ▶")
        self.next_btn.setObjectName("secondary")
        self.next_btn.setFixedWidth(100)
        self.next_btn.clicked.connect(self.go_next_page)
        
        pagination_layout.addWidget(self.prev_btn)
        pagination_layout.addWidget(self.page_lbl, 1)
        pagination_layout.addWidget(self.next_btn)
        
        table_card_layout.addLayout(pagination_layout)
        main_layout.addWidget(table_card, 1)
        
        # ==========================================
        # 5. BOTTOM BAR ACTIONS
        # ==========================================
        bottom_layout = QtWidgets.QHBoxLayout()
        self.refresh_btn = QtWidgets.QPushButton("Refresh Database")
        self.refresh_btn.setObjectName("secondary")
        self.refresh_btn.clicked.connect(self.load_reports)
        
        self.bulk_csv_btn = QtWidgets.QPushButton("Bulk Export CSV")
        self.bulk_csv_btn.clicked.connect(self.export_bulk_csv)
        
        bottom_layout.addWidget(self.refresh_btn)
        bottom_layout.addStretch()

        if self._is_superadmin():
            self.clear_all_btn = QtWidgets.QPushButton("Clear All Reports")
            self.clear_all_btn.setObjectName("clearAllBtn")
            self.clear_all_btn.clicked.connect(self.clear_all_reports)
            bottom_layout.addWidget(self.clear_all_btn)
        else:
            self.clear_all_btn = None

        bottom_layout.addWidget(self.bulk_csv_btn)
        main_layout.addLayout(bottom_layout)

    def _is_superadmin(self):
        return (self.user or {}).get("role", "").lower() == "superadmin"

    def clear_all_reports(self):
        if not self._is_superadmin():
            CustomDialog.warning(
                self,
                "Access Denied",
                "You do not have permission to clear all reports.",
                description="Only Super Admin users may perform this action.",
            )
            return

        reply = CustomDialog.question(
            self,
            "Clear All Reports",
            "You are about to permanently delete ALL reports and all associated measurement timeline data.",
            description="This action cannot be undone.",
            buttons=["Clear All Reports", "Cancel"],
            default_button="Cancel",
        )
        if reply != CustomDialog.Yes:
            return

        username = (self.user or {}).get("username", "system")
        role = (self.user or {}).get("role", "")

        try:
            result = self.report_manager.clear_all_reports(
                username=username,
                role=role,
                reason="Manual Maintenance",
            )
            self.current_page = 1
            self.load_reports()

            parent = self.window()
            if parent and hasattr(parent, "update_stats"):
                parent.update_stats()
            if parent and hasattr(parent, "refresh_data_views"):
                parent.refresh_data_views()

            CustomDialog.success(
                self,
                "Reports Cleared",
                "All reports and timeline data have been permanently deleted.",
                description=(
                    f"Deleted Reports: {result['report_count']}\n"
                    f"Deleted Timeline Samples: {result['sample_count']}\n\n"
                    "New reports will start from ID 1."
                ),
            )
        except ReportClearPermissionError:
            CustomDialog.warning(
                self,
                "Access Denied",
                "You do not have permission to clear all reports.",
                description="Only Super Admin users may perform this action.",
            )
        except Exception as exc:
            import traceback
            CustomDialog.critical(
                self,
                "Clear Failed",
                "Could not clear all reports. No records were deleted.",
                details=traceback.format_exc() if str(exc) else str(exc),
            )

    # ==========================================
    # DATABASE & PAGINATION LOGIC
    # ==========================================
    def load_reports(self):
        """Initiate database fetch with loading overlay spinner simulated."""
        self.stacked_view.setCurrentIndex(1) # Loading view
        self.search_btn.setEnabled(False)
        self.reset_btn.setEnabled(False)
        
        # Fetch matching rows after a tiny layout update delay (simulates professional load animation)
        QtCore.QTimer.singleShot(250, self.fetch_data_from_db)

    def fetch_data_from_db(self):
        try:
            mat = self.filter_material.text().strip()
            op = self.filter_operator.text().strip()
            dt = self.filter_date.text().strip()
            smp = self.filter_sample.text().strip()
            tst = self.filter_test.text().strip()
            
            raw_reports = self.report_manager.get_reports_filtered(
                material=mat,
                username=op,
                date_str=dt,
                sample_name=smp,
                test_name=tst
            )
            
            # Map database list to structured dicts
            self.all_reports = []
            for r in raw_reports:
                self.all_reports.append({
                    'id': r[0],
                    'username': r[1],
                    'gauge_length': r[2] if r[2] else 0.0,
                    'initial_distance': r[3] if r[3] else 0.0,
                    'final_distance': r[4] if r[4] else 0.0,
                    'strain': r[5] if r[5] else 0.0,
                    'created_at': r[6] if r[6] else "",
                    'material': r[7] if r[7] else "N/A",
                    'sample_name': r[8] if r[8] else "N/A",
                    'test_name': r[9] if r[9] else "N/A",
                    'operator': r[10] if r[10] else (r[1] if r[1] else "N/A"),
                    'remarks': r[11] if r[11] else "",
                    'camera_resolution': r[12] if r[12] else "Unknown",
                    'software_version': r[13] if r[13] else "v2.5.0"
                })
            
            self.update_statistics()
            if hasattr(self, 'keep_page_on_reload') and self.keep_page_on_reload:
                total = len(self.all_reports)
                total_pages = max(1, math.ceil(total / self.items_per_page))
                if self.current_page > total_pages:
                    self.current_page = total_pages
                self.keep_page_on_reload = False
            else:
                self.current_page = 1
            self.refresh_table_view()
            
        except Exception as e:
            print(f"[ERROR] Failed to query reports: {e}")
            CustomDialog.critical(self, "Query Error", "Failed to load reports from database.", details=str(e))
            self.stacked_view.setCurrentIndex(2) # Fallback to empty/error representation
            
        finally:
            self.search_btn.setEnabled(True)
            self.reset_btn.setEnabled(True)

    def _animate_kpi_value(self, label):
        effect = QtWidgets.QGraphicsOpacityEffect(label)
        label.setGraphicsEffect(effect)
        anim = QtCore.QPropertyAnimation(effect, b"opacity", label)
        anim.setDuration(180)
        anim.setStartValue(0.55)
        anim.setEndValue(1.0)
        anim.start(QtCore.QAbstractAnimation.DeleteWhenStopped)

    def _kpi_value_style(self, label, *, placeholder=False):
        if label is self.val_avg_strain:
            if placeholder:
                return "font-size: 13px; font-weight: 600; color: #64748b;"
            return "font-size: 32px; font-weight: bold; color: #fbbf24;"
        return "font-size: 32px; font-weight: bold; color: #f8fafc;"

    def _set_kpi_value(self, label, text, *, placeholder=False):
        style = self._kpi_value_style(label, placeholder=placeholder)
        if label.text() != text or label.styleSheet() != style:
            label.setText(text)
            label.setStyleSheet(style)
            self._animate_kpi_value(label)

    def _fetch_total_report_count(self):
        cur = self.report_manager.db.conn.cursor()
        cur.execute("SELECT COUNT(*) FROM reports")
        count = cur.fetchone()[0]
        cur.close()
        return count

    def _report_by_id(self, report_id):
        for report in self.all_reports:
            if report["id"] == report_id:
                return report
        return None

    def _selected_report_strains(self):
        strains = []
        selected_rows = sorted({index.row() for index in self.table.selectedIndexes()})
        for row in selected_rows:
            id_item = self.table.item(row, 0)
            if not id_item:
                continue
            try:
                report_id = int(id_item.text())
            except ValueError:
                continue
            report = self._report_by_id(report_id)
            if report is not None:
                strains.append(report["strain"])
        return strains

    def on_table_selection_changed(self):
        self.update_average_strain_from_selection()

    def update_total_reports(self):
        try:
            total = self._fetch_total_report_count()
            self._set_kpi_value(self.val_total, str(total))
        except Exception as e:
            print(f"[ERROR] Failed to update total reports KPI: {e}")

    def update_average_strain_from_selection(self):
        strains = self._selected_report_strains()
        if not strains:
            placeholder = "Select Report" if self.all_reports else "—"
            self._set_kpi_value(self.val_avg_strain, placeholder, placeholder=True)
            return
        avg_strain = sum(strains) / len(strains)
        self._set_kpi_value(
            self.val_avg_strain,
            f"{avg_strain * 100:+.3f} %",
            placeholder=False,
        )

    def update_statistics(self):
        """Refresh KPI cards after database or selection changes."""
        self.update_total_reports()
        self.update_average_strain_from_selection()

    def refresh_table_view(self):
        """Renders the slice of data corresponding to the current page index."""
        self.table.setSortingEnabled(False)  # Disable during insertion
        total = len(self.all_reports)
        
        if total == 0:
            self.stacked_view.setCurrentIndex(2) # Empty state index
            self.prev_btn.setEnabled(False)
            self.next_btn.setEnabled(False)
            self.page_lbl.setText("Page 0 of 0")
            self.table.clearSelection()
            self.update_statistics()
            return
            
        self.stacked_view.setCurrentIndex(0) # Table index
        
        self.total_pages = max(1, math.ceil(total / self.items_per_page))
        if self.current_page > self.total_pages:
            self.current_page = self.total_pages
            
        # Slice reports list
        start = (self.current_page - 1) * self.items_per_page
        end = start + self.items_per_page
        page_items = self.all_reports[start:end]
        
        self.table.setRowCount(len(page_items))
        
        for row_idx, r in enumerate(page_items):
            # Columns list: ID (0), Material (1), Sample Name (2), User (3), Gauge Length (4), Initial Distance (5), Final Distance (6), Strain (7), Date (8), Actions (9)
            
            # Row cells
            def make_item(text, alignment=QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter):
                it = QtWidgets.QTableWidgetItem(text)
                it.setFlags(it.flags() & ~QtCore.Qt.ItemIsEditable)
                it.setTextAlignment(alignment)
                return it

            self.table.setItem(row_idx, 0, make_item(str(r['id']), QtCore.Qt.AlignCenter))
            self.table.setItem(row_idx, 1, make_item(r['material']))
            self.table.setItem(row_idx, 2, make_item(r['sample_name']))
            self.table.setItem(row_idx, 3, make_item(r['operator']))
            self.table.setItem(row_idx, 4, make_item(f"{r['gauge_length']:.2f} mm", QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter))
            self.table.setItem(row_idx, 5, make_item(f"{r['initial_distance']:.2f} mm", QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter))
            self.table.setItem(row_idx, 6, make_item(f"{r['final_distance']:.2f} mm", QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter))
            self.table.setItem(row_idx, 7, make_item(f"{r['strain']:+.6f}", QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter))
            
            # Formatting Date
            dt_display = r['created_at'].split(" ")[0] if " " in r['created_at'] else r['created_at']
            self.table.setItem(row_idx, 8, make_item(dt_display, QtCore.Qt.AlignCenter))
            
            # 9. Inline Action buttons
            action_widget = QtWidgets.QWidget()
            action_layout = QtWidgets.QHBoxLayout(action_widget)
            action_layout.setContentsMargins(6, 2, 6, 2)
            action_layout.setSpacing(6)
            action_layout.setAlignment(QtCore.Qt.AlignCenter)
            
            def make_act_btn(lbl, handler, is_delete=False):
                btn = QtWidgets.QPushButton(lbl)
                btn.setObjectName("tableActionDeleteBtn" if is_delete else "tableActionBtn")
                btn.setStyleSheet(self.styleSheet())
                btn.setProperty("report_id", r['id'])
                btn.clicked.connect(handler)
                action_layout.addWidget(btn)
                
            make_act_btn("View", self.on_action_view_clicked)
            make_act_btn("PDF", self.on_action_pdf_clicked)
            make_act_btn("CSV", self.on_action_csv_clicked)
            make_act_btn("Delete", self.on_action_delete_clicked, is_delete=True)
            
            self.table.setCellWidget(row_idx, 9, action_widget)
            
        # Update pagination widgets
        self.page_lbl.setText(f"Page {self.current_page} of {self.total_pages} (Total Records: {total})")
        self.prev_btn.setEnabled(self.current_page > 1)
        self.next_btn.setEnabled(self.current_page < self.total_pages)
        self.update_statistics()
        
        self.table.setSortingEnabled(True)
        print("[REPORT TABLE REFRESHED]")

    # ==========================================
    # ACTION HANDLERS
    # ==========================================
    def on_search_clicked(self):
        self.load_reports()

    def on_reset_clicked(self):
        self.filter_material.clear()
        self.filter_operator.clear()
        self.filter_date.clear()
        self.filter_sample.clear()
        self.filter_test.clear()
        self.load_reports()

    def go_prev_page(self):
        if self.current_page > 1:
            self.current_page -= 1
            self.refresh_table_view()

    def go_next_page(self):
        if self.current_page < self.total_pages:
            self.current_page += 1
            self.refresh_table_view()

    def on_row_double_clicked(self, index):
        """Open detailed report dialog on row double click."""
        row = index.row()
        report_id_str = self.table.item(row, 0).text()
        try:
            report_id = int(report_id_str)
            self.show_details_by_id(report_id)
        except Exception as e:
            print(f"[ERROR] Failed to map double clicked report ID: {e}")

    def on_action_view_clicked(self):
        btn = self.sender()
        report_id = btn.property("report_id")
        if report_id:
            self.show_details_by_id(report_id)

    def show_details_by_id(self, report_id):
        # Find matching dictionary in cached results
        report_data = None
        for r in self.all_reports:
            if r['id'] == report_id:
                report_data = r
                break
        
        if report_data:
            dlg = ReportDetailsDialog(report_data, self)
            dlg.exec_()

    # ==========================================
    # PDF & CSV COMPILER LOGIC
    # ==========================================
    def on_action_pdf_clicked(self):
        btn = self.sender()
        report_id = btn.property("report_id")
        if report_id:
            # Find report data
            for r in self.all_reports:
                if r['id'] == report_id:
                    self.render_report_pdf(r)
                    break

    def on_action_csv_clicked(self):
        btn = self.sender()
        report_id = btn.property("report_id")
        if report_id:
            for r in self.all_reports:
                if r['id'] == report_id:
                    self.render_report_csv(r)
                    break

    def on_action_delete_clicked(self):
        btn = self.sender()
        report_id = btn.property("report_id")
        if not report_id:
            return
            
        print("[DELETE CLICKED]")
        print(f"Selected Report ID: {report_id}")
        
        report_data = None
        for r in self.all_reports:
            if r['id'] == report_id:
                report_data = r
                break
                
        if not report_data:
            report_data = {
                'id': report_id,
                'material': "N/A",
                'operator': "N/A",
                'created_at': "N/A"
            }
            
        description_text = (
            f"Report ID: {report_data['id']}\n"
            f"Material: {report_data['material']}\n"
            f"Operator: {report_data['operator']}\n"
            f"Date: {report_data['created_at']}\n\n"
            f"Warning: This action cannot be undone."
        )
        
        reply = CustomDialog.question(
            self,
            "Delete Report",
            "Are you sure you want to permanently delete this report?",
            description=description_text,
            buttons=["Delete Report", "Cancel"],
            default_button="Cancel"
        )
        
        if reply == CustomDialog.Yes:
            try:
                self.keep_page_on_reload = True
                self.report_manager.delete_report(report_id)

                actor = ""
                actor_role = ""
                if self.user and isinstance(self.user, dict):
                    actor = self.user.get("username", "")
                    actor_role = self.user.get("role", "")
                self.audit.log_event(
                    action="Report Deleted",
                    username=actor,
                    role=actor_role,
                    result="Success",
                    details=f"Report ID {report_id}",
                )
                
                # Refresh dashboard stats
                parent = self.window()
                if hasattr(parent, "update_stats"):
                    parent.update_stats()
                    
                self.load_reports()
                
                CustomDialog.success(
                    self,
                    "Report Deleted",
                    "The selected report has been permanently removed.",
                    buttons=["OK"]
                )
            except Exception as e:
                import traceback
                details = traceback.format_exc()
                print(f"[ERROR] Deletion failed: {e}")
                CustomDialog.critical(
                    self,
                    "Delete Failed",
                    "Failed to delete report.",
                    details=details,
                    buttons=["OK"]
                )

    def render_report_pdf(self, report_data):
        """Redesign ReportLab PDF with corporate logo, blue header layout, and paginated table spacing."""
        try:
            default_name = f"report_{report_data['id']}.pdf"
            options = QtWidgets.QFileDialog.Options()
            file_path, _ = QtWidgets.QFileDialog.getSaveFileName(
                self,
                "Save PDF Report",
                default_name,
                "PDF Files (*.pdf);;All Files (*)",
                options=options
            )
            
            if not file_path:
                return
                
            if not file_path.endswith(".pdf"):
                file_path += ".pdf"
                
            doc = SimpleDocTemplate(
                file_path,
                pagesize=letter,
                rightMargin=54,
                leftMargin=54,
                topMargin=54,
                bottomMargin=60  # Space for NumberedCanvas footer
            )
            
            story = []
            styles = getSampleStyleSheet()
            
            # Typography configurations
            company_style = ParagraphStyle(
                name='CorpHeaderCompany',
                parent=styles['Normal'],
                fontName='Helvetica-Bold',
                fontSize=14,
                leading=16,
                textColor=colors.HexColor('#ffffff')
            )
            
            report_title_style = ParagraphStyle(
                name='CorpHeaderTitle',
                parent=styles['Normal'],
                fontName='Helvetica-Bold',
                fontSize=16,
                leading=18,
                textColor=colors.HexColor('#ffffff'),
                alignment=2  # Right-aligned
            )
            
            section_title_style = ParagraphStyle(
                name='SectionTitle',
                parent=styles['Normal'],
                fontName='Helvetica-Bold',
                fontSize=11,
                leading=14,
                textColor=colors.HexColor('#1e3a8a'),
                spaceBefore=14,
                spaceAfter=6
            )
            
            label_style = ParagraphStyle(
                name='PDFLabel',
                parent=styles['Normal'],
                fontName='Helvetica-Bold',
                fontSize=9,
                leading=11,
                textColor=colors.HexColor('#475569')
            )
            
            value_style = ParagraphStyle(
                name='PDFValue',
                parent=styles['Normal'],
                fontName='Helvetica',
                fontSize=9,
                leading=11,
                textColor=colors.HexColor('#0f172a')
            )
            
            col_header_style = ParagraphStyle(
                name='ColHeader',
                parent=styles['Normal'],
                fontName='Helvetica-Bold',
                fontSize=9,
                leading=11,
                textColor=colors.HexColor('#ffffff')
            )
            
            label_highlight_style = ParagraphStyle(
                name='HighlightLabel',
                parent=styles['Normal'],
                fontName='Helvetica-Bold',
                fontSize=10,
                leading=12,
                textColor=colors.HexColor('#1e3a8a')
            )
            
            value_highlight_style = ParagraphStyle(
                name='HighlightValue',
                parent=styles['Normal'],
                fontName='Helvetica-Bold',
                fontSize=10,
                leading=12,
                textColor=colors.HexColor('#1e40af')
            )
            
            remarks_style = ParagraphStyle(
                name='RemarksText',
                parent=styles['Normal'],
                fontName='Helvetica-Oblique',
                fontSize=9,
                leading=12,
                textColor=colors.HexColor('#334155')
            )

            # 1. Company Banner (Header)
            company = CompanyManager.get_instance()
            profile = company.get_profile()
            company_name = profile.get("company_name", "")
            report_title = profile.get("report_title", "VIDEO EXTENSOMETER TEST REPORT")
            address_block = company.format_address_block(profile).replace("\n", "<br/>")
            contact_line = company.format_contact_line(profile)

            logo_path = company.get_pdf_logo_path()
            left_cell = []
            if logo_path and os.path.isfile(logo_path):
                left_cell.append(RLImage(logo_path, width=120, height=40))
                left_cell.append(Spacer(1, 6))
            left_cell.append(
                Paragraph(
                    f"<font size=12 color=white><b>{company_name}</b></font>",
                    company_style,
                )
            )
            if address_block:
                left_cell.append(
                    Paragraph(
                        f"<font size=8 color='#cbd5e1'>{address_block}</font>",
                        company_style,
                    )
                )
            if contact_line:
                left_cell.append(
                    Paragraph(
                        f"<font size=8 color='#93c5fd'>{contact_line}</font>",
                        company_style,
                    )
                )

            header_data = [
                [
                    left_cell,
                    Paragraph(
                        f"<font size=14 color=white>{report_title}</font>",
                        report_title_style,
                    ),
                ]
            ]
            header_table = Table(header_data, colWidths=[240, 264])
            header_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#1e3a8a')),
                ('ALIGN', (0,0), (0,0), 'LEFT'),
                ('ALIGN', (1,0), (1,0), 'RIGHT'),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ('TOPPADDING', (0,0), (-1,-1), 12),
                ('BOTTOMPADDING', (0,0), (-1,-1), 12),
                ('LEFTPADDING', (0,0), (-1,-1), 16),
                ('RIGHTPADDING', (0,0), (-1,-1), 16),
            ]))
            story.append(header_table)
            story.append(Spacer(1, 10))

            # 2. General Information Section
            story.append(Paragraph("1. GENERAL TEST METADATA", section_title_style))
            gen_data = [
                [Paragraph("Material", label_style), Paragraph(report_data['material'], value_style),
                 Paragraph("Test Sequence Date", label_style), Paragraph(report_data['created_at'], value_style)],
                [Paragraph("Sample Name", label_style), Paragraph(report_data['sample_name'], value_style),
                 Paragraph("Authorized Operator", label_style), Paragraph(report_data['operator'], value_style)],
                [Paragraph("Test Profile Name", label_style), Paragraph(report_data['test_name'], value_style),
                 Paragraph("Report Database ID", label_style), Paragraph(str(report_data['id']), value_style)]
            ]
            gen_table = Table(gen_data, colWidths=[90, 160, 110, 144])
            gen_table.setStyle(TableStyle([
                ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ('TOPPADDING', (0,0), (-1,-1), 6),
                ('BOTTOMPADDING', (0,0), (-1,-1), 6),
                ('LEFTPADDING', (0,0), (-1,-1), 8),
                ('RIGHTPADDING', (0,0), (-1,-1), 8),
                ('LINEBELOW', (0,0), (-1,-1), 0.5, colors.HexColor('#f1f5f9')),
                ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8fafc')),
                ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
            ]))
            story.append(gen_table)
            story.append(Spacer(1, 10))

            # 3. Measurement Section
            story.append(Paragraph("2. QUANTITATIVE MEASUREMENT RESULTS", section_title_style))
            
            ext_val = report_data['final_distance'] - report_data['initial_distance']
            
            meas_data = [
                [Paragraph("Measured Parameter", col_header_style), Paragraph("Calculated Value (Metric Space)", col_header_style)],
                [Paragraph("Pre-test Gauge Reference Length (L₀)", label_style), Paragraph(f"{report_data['gauge_length']:.2f} mm", value_style)],
                [Paragraph("Optical Initial Marker Distance (d₀)", label_style), Paragraph(f"{report_data['initial_distance']:.2f} mm", value_style)],
                [Paragraph("Optical Final Marker Distance (d_f)", label_style), Paragraph(f"{report_data['final_distance']:.2f} mm", value_style)],
                [Paragraph("Total Physical Extension (Δd)", label_style), Paragraph(f"{ext_val:+.2f} mm", value_style)],
                [Paragraph("<b>Peak Strain Yield (ε)</b>", label_highlight_style), Paragraph(f"<b>{report_data['strain']:+.6f}</b>", value_highlight_style)]
            ]
            meas_table = Table(meas_data, colWidths=[230, 274])
            meas_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#2563eb')),
                ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ('TOPPADDING', (0,0), (-1,-1), 7),
                ('BOTTOMPADDING', (0,0), (-1,-1), 7),
                ('LEFTPADDING', (0,0), (-1,-1), 10),
                ('RIGHTPADDING', (0,0), (-1,-1), 10),
                ('LINEBELOW', (0,1), (-1,-2), 0.5, colors.HexColor('#f1f5f9')),
                ('BACKGROUND', (0,1), (-1,-2), colors.HexColor('#f8fafc')),
                ('BACKGROUND', (0,-1), (-1,-1), colors.HexColor('#dbeafe')),
                ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor('#2563eb')),
            ]))
            story.append(meas_table)
            story.append(Spacer(1, 10))

            timeline_stats = self.sample_manager.get_timeline_stats(report_data["id"])
            samples = self.sample_manager.get_samples(report_data["id"])
            duration_text = SampleManager.format_duration(
                timeline_stats.get("test_duration")
            )

            story.append(Paragraph("3. MEASUREMENT TIMELINE SUMMARY", section_title_style))
            summary_data = [
                [Paragraph("Metric", col_header_style), Paragraph("Value", col_header_style)],
                [Paragraph("Test Duration", label_style), Paragraph(duration_text, value_style)],
                [Paragraph("Total Samples Recorded", label_style),
                 Paragraph(str(timeline_stats.get("total_samples", 0)), value_style)],
                [Paragraph("Maximum Strain (ε)", label_style),
                 Paragraph(
                     f"{timeline_stats['max_strain']:+.6f}"
                     if timeline_stats.get("max_strain") is not None else "—",
                     value_style,
                 )],
                [Paragraph("Average Strain (ε)", label_style),
                 Paragraph(
                     f"{timeline_stats['avg_strain']:+.6f}"
                     if timeline_stats.get("avg_strain") is not None else "—",
                     value_style,
                 )],
                [Paragraph("Maximum Extension (mm)", label_style),
                 Paragraph(
                     f"{timeline_stats['max_extension']:+.3f}"
                     if timeline_stats.get("max_extension") is not None else "—",
                     value_style,
                 )],
                [Paragraph("Average Extension (mm)", label_style),
                 Paragraph(
                     f"{timeline_stats['avg_extension']:+.3f}"
                     if timeline_stats.get("avg_extension") is not None else "—",
                     value_style,
                 )],
            ]
            summary_table = Table(summary_data, colWidths=[230, 274])
            summary_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#2563eb')),
                ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ('TOPPADDING', (0,0), (-1,-1), 7),
                ('BOTTOMPADDING', (0,0), (-1,-1), 7),
                ('LEFTPADDING', (0,0), (-1,-1), 10),
                ('LINEBELOW', (0,1), (-1,-2), 0.5, colors.HexColor('#f1f5f9')),
                ('BACKGROUND', (0,1), (-1,-1), colors.HexColor('#f8fafc')),
                ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor('#2563eb')),
            ]))
            story.append(summary_table)
            story.append(Spacer(1, 10))

            if samples:
                strain_chart, distance_chart = self.sample_manager.generate_timeline_chart_images(
                    samples, report_data["id"]
                )
                if strain_chart and os.path.exists(strain_chart):
                    story.append(Paragraph("4. STRAIN VS TIME", section_title_style))
                    story.append(RLImage(strain_chart, width=504, height=210))
                    story.append(Spacer(1, 8))
                if distance_chart and os.path.exists(distance_chart):
                    story.append(Paragraph("5. DISTANCE VS TIME", section_title_style))
                    story.append(RLImage(distance_chart, width=504, height=210))
                    story.append(Spacer(1, 10))

            # Tracking and System Context Section
            story.append(Paragraph("6. ACQUISITION & HARDWARE CONFIGURATION", section_title_style))
            sys_data = [
                [Paragraph("Camera Image Resolution", label_style), Paragraph(report_data['camera_resolution'], value_style),
                 Paragraph("Software Stack Version", label_style), Paragraph(report_data['software_version'], value_style)],
                [Paragraph("Account ID Session", label_style), Paragraph(report_data['username'], value_style),
                 Paragraph("Measurement Integrity Trace", label_style), Paragraph("Verified (Optical Flow)", value_style)]
            ]
            sys_table = Table(sys_data, colWidths=[150, 100, 150, 104])
            sys_table.setStyle(TableStyle([
                ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ('TOPPADDING', (0,0), (-1,-1), 6),
                ('BOTTOMPADDING', (0,0), (-1,-1), 6),
                ('LEFTPADDING', (0,0), (-1,-1), 8),
                ('LINEBELOW', (0,0), (-1,-1), 0.5, colors.HexColor('#f1f5f9')),
                ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8fafc')),
                ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
            ]))
            story.append(sys_table)
            story.append(Spacer(1, 10))

            # Remarks / Comments Card
            story.append(Paragraph("7. OPERATOR REMARKS / OBSERVATIONS", section_title_style))
            remarks_text = report_data['remarks'] if report_data['remarks'] else "No comments entered for this tensile inspection sequence."
            remarks_p = Paragraph(remarks_text, remarks_style)
            remarks_table = Table([[remarks_p]], colWidths=[504])
            remarks_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8fafc')),
                ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
                ('TOPPADDING', (0,0), (-1,-1), 8),
                ('BOTTOMPADDING', (0,0), (-1,-1), 8),
                ('LEFTPADDING', (0,0), (-1,-1), 10),
                ('RIGHTPADDING', (0,0), (-1,-1), 10),
            ]))
            story.append(remarks_table)

            # Build document with multi-pass NumberedCanvas footer
            doc.build(story, canvasmaker=NumberedCanvas)
            print("[PDF GENERATED]")

            actor = ""
            actor_role = ""
            if self.user and isinstance(self.user, dict):
                actor = self.user.get("username", "")
                actor_role = self.user.get("role", "")
            self.audit.log_event(
                action="PDF Export",
                username=actor,
                role=actor_role,
                result="Success",
                details=file_path,
            )
            
            CustomDialog.pdf_success(self, file_path)
            
        except Exception as e:
            print(f"[ERROR] Failed to compile PDF: {e}")
            CustomDialog.critical(self, "Export Error", "Failed to generate PDF Report.", details=str(e))

    def render_report_csv(self, report_data):
        """Export single report details to a CSV matching all database fields."""
        try:
            default_name = f"report_{report_data['id']}.csv"
            options = QtWidgets.QFileDialog.Options()
            file_path, _ = QtWidgets.QFileDialog.getSaveFileName(
                self,
                "Save CSV Report",
                default_name,
                "CSV Files (*.csv);;All Files (*)",
                options=options
            )
            
            if not file_path:
                return
                
            if not file_path.endswith(".csv"):
                file_path += ".csv"
                
            with open(file_path, "w", newline="", encoding="utf-8") as f:
                writer = csv.writer(f)
                company = CompanyManager.get_instance()
                for row in company.csv_header_rows():
                    writer.writerow(row)
                ext_val = report_data['final_distance'] - report_data['initial_distance']
                samples = self.sample_manager.get_samples(report_data["id"])
                timeline_stats = self.sample_manager.get_timeline_stats(report_data["id"])
                duration_text = SampleManager.format_duration(
                    timeline_stats.get("test_duration")
                )

                writer.writerow(["Report Information"])
                writer.writerow(["Report ID", report_data["id"]])
                writer.writerow(["Operator", report_data["operator"]])
                writer.writerow(["Material", report_data["material"]])
                writer.writerow(["Sample Name", report_data["sample_name"]])
                writer.writerow(["Gauge Length (mm)", f"{report_data['gauge_length']:.3f}"])
                writer.writerow(["Final Distance (mm)", f"{report_data['final_distance']:.3f}"])
                writer.writerow(["Extension (mm)", f"{ext_val:.3f}"])
                writer.writerow(["Final Strain", f"{report_data['strain']:.6f}"])
                writer.writerow(["Test Duration", duration_text])
                writer.writerow(["Date", report_data["created_at"]])
                writer.writerow([])
                writer.writerow(["Timeline Statistics"])
                writer.writerow(["Total Samples", timeline_stats.get("total_samples", 0)])
                if timeline_stats.get("max_strain") is not None:
                    writer.writerow(["Maximum Strain", f"{timeline_stats['max_strain']:.6f}"])
                    writer.writerow(["Average Strain", f"{timeline_stats['avg_strain']:.6f}"])
                if timeline_stats.get("max_extension") is not None:
                    writer.writerow(["Maximum Extension", f"{timeline_stats['max_extension']:.3f}"])
                    writer.writerow(["Average Extension", f"{timeline_stats['avg_extension']:.3f}"])
                writer.writerow([])
                writer.writerow(["Timeline"])
                writer.writerow(["Time", "Distance", "Extension", "Strain"])
                for elapsed, distance, extension, strain in samples:
                    writer.writerow([
                        f"{elapsed:.3f}",
                        f"{distance:.3f}",
                        f"{extension:.3f}",
                        f"{strain:.6f}",
                    ])
                
            print("[CSV EXPORTED]")

            actor = ""
            actor_role = ""
            if self.user and isinstance(self.user, dict):
                actor = self.user.get("username", "")
                actor_role = self.user.get("role", "")
            self.audit.log_event(
                action="CSV Export",
                username=actor,
                role=actor_role,
                result="Success",
                details=file_path,
            )

            CustomDialog.csv_success(self, file_path)
            
        except Exception as e:
            print(f"[ERROR] Failed to export CSV: {e}")
            CustomDialog.critical(self, "Export Error", "Failed to generate CSV Report.", details=str(e))

    def export_bulk_csv(self):
        """Export all current filtered records in a single bulk CSV file."""
        if not self.all_reports:
            CustomDialog.warning(self, "Export Refused", "No records available in active filter to export.")
            return
            
        try:
            default_name = datetime.now().strftime("bulk_reports_%Y%m%d_%H%M%S.csv")
            options = QtWidgets.QFileDialog.Options()
            file_path, _ = QtWidgets.QFileDialog.getSaveFileName(
                self,
                "Save Bulk CSV Report",
                default_name,
                "CSV Files (*.csv);;All Files (*)",
                options=options
            )
            
            if not file_path:
                return
                
            if not file_path.endswith(".csv"):
                file_path += ".csv"
                
            with open(file_path, "w", newline="", encoding="utf-8") as f:
                writer = csv.writer(f)
                company = CompanyManager.get_instance()
                for row in company.csv_header_rows():
                    writer.writerow(row)
                writer.writerow([
                    "Report ID", "Material", "Sample Name", "Test Name", "Operator",
                    "Gauge Length (mm)", "Initial Distance (mm)", "Final Distance (mm)",
                    "Extension (mm)", "Strain", "Camera Resolution", "Software Version",
                    "User", "Remarks", "Date & Time"
                ])
                
                for r in self.all_reports:
                    ext_val = r['final_distance'] - r['initial_distance']
                    writer.writerow([
                        r['id'],
                        r['material'],
                        r['sample_name'],
                        r['test_name'],
                        r['operator'],
                        f"{r['gauge_length']:.2f}",
                        f"{r['initial_distance']:.2f}",
                        f"{r['final_distance']:.2f}",
                        f"{ext_val:+.2f}",
                        f"{r['strain']:.6f}",
                        r['camera_resolution'],
                        r['software_version'],
                        r['username'],
                        r['remarks'],
                        r['created_at']
                    ])
                    
            print("[BULK CSV EXPORTED]")

            actor = ""
            actor_role = ""
            if self.user and isinstance(self.user, dict):
                actor = self.user.get("username", "")
                actor_role = self.user.get("role", "")
            self.audit.log_event(
                action="CSV Export",
                username=actor,
                role=actor_role,
                result="Success",
                details=f"Bulk export: {file_path}",
            )

            CustomDialog.csv_success(self, file_path)
            
        except Exception as e:
            print(f"[ERROR] Failed to export bulk CSV: {e}")
            CustomDialog.critical(self, "Export Error", "Failed to compile bulk CSV.", details=str(e))
